image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
  - cmd: nuget install NUnit.Console -Version 3.7.0 -OutputDirectory tools
  - cmd: nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - cmd: nuget restore
  - cmd: choco install codecov
build:
  project: CDP4-SDK.sln
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
  categories:
    except:
      - AppVeyorExclusion
after_test:
  - .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\tools\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:".\CDP4Common.Tests\bin\Debug\net462\CDP4Common.Tests.dll .\CDP4Dal.Tests\bin\Debug\net462\CDP4Dal.Tests.dll .\CDP4JsonFileDal.Tests\bin\Debug\net462\CDP4JsonFileDal.Tests.dll .\CDP4JsonSerializer.Tests\bin\Debug\net462\CDP4JsonSerializer.Tests.dll .\CDP4ServicesDal.Tests\bin\Debug\net462\CDP4ServicesDal.Tests.dll .\CDP4WspDal.Tests\bin\Debug\net462\CDP4WspDal.Tests.dll" -filter:"+[CDP4Common*]* -[CDP4Common.Tests*]* +[CDP4Dal*]* -[CDP4Dal.Tests*]* +[*CDP4JsonFileDal]* -[CDP4JsonFileDal.Tests*]* +[CDP4JsonSerializer*]* -[CDP4JsonSerializer.Tests*]* +[CDP4ServicesDal*]* -[CDP4ServicesDal.Tests*]* +[CDP4WspDal*]* -[CDP4WspDal.Tests*]*" -output:"coverage.xml"
  - codecov -f "coverage.xml" -t b8924a0f-355e-4a9a-b304-f403231a6bcb