image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
  - cmd: nuget restore
build:
  project: CDP4-SDK.sln
test:
  assemblies:
    only:
      - '**\CDP4JsonFileDal.Tests.dll'
  categories:
    except:
      - AppVeyorExclusion